AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb' # Exclude block length check for spec files
